# Generated by Django 4.0.6 on 2022-08-02 11:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='link',
            name='link',
            field=models.URLField(max_length=1000),
        ),
        migrations.AlterField(
            model_name='link',
            name='shortlink',
            field=models.URLField(max_length=1000),
        ),
    ]
